config:
    custom: aoeu
    duration: 10s
    number: 1234

list:
    entries:
        - a
        - b
        - c
    nested:
        - key: k1
          value: v1
        - key: k2
          value: v2

custom:
    port: 6711

web:
    port: 3367

amqp:
    amqp:
        user: uhe
        pass: roh
        host: hih
        port: 870
    custom:
        user: rtn
        pass: kbo
        host: aar
        port: 473

postgres:
    postgres:
        user: ter
        host: hor
        port: 4711
        db: 41
    custom:
        user: orr
        host: obk
        db: 11

redis:
    redis:
        host: ecr
        port: 340
        db: 16
    custom:
        host: ruo
        port: 114
        db: 81

graphite:
    graphite:
        host: ghost
        port: 4177
